name: Generate SBOM with Snyk

# Allow the workflow to be manually triggered
on:
  workflow_dispatch:  # This enables manual running of the workflow
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (only necessary if you're scanning a Node.js project)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Adjust the version as needed

    # Step 3: Install snyk-cli
    - name: Install Snyk CLI
      run: npm install -g snyk

    # Step 4: Authenticate Snyk (you can use Snyk token from GitHub Secrets)
    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # Step 5: Generate SBOM in CycloneDX format
    - name: Generate SBOM
      run: snyk sbom --format=cyclonedx1.4+json > snyk-sbom.json

    # Step 6: Upload SBOM as an artifact (optional, useful for later download)
    - name: Upload SBOM as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: snyk-sbom
        path: snyk-sbom.json
